### ISSUE TITLE
Does not work in Ubuntu 16.04

### ISSUE THREAD

**Issue by darren12345** [ariacorrente/simple-sort-bookmarks#11]
I have this installed on a few different machines. On Ubuntu, if I create a new bookmark it does not get sorted. I have automatic sorting enabled. Thanks.

Ubuntu and Firefox are fully up to date.

**Comment by ariacorrente** [comment]
Sorry, I read this issue i but i forgot to reply. I hope you are still interested in solving this.

This is the second time an user using Ubuntu reports about the addon not working. This is quite strange because the addon is developed and used on my computer using Kubuntu and i presume the Firefox binary are the same of Ubuntu.

Maybe something went wrong in the configuration?  can you take a screenshot of the basic and the  advanced settings page?
Have you tried to uninstall and reinstall the addon to clean up the configuration?

A feature to allow the user to easily generate a "debug report" may be useful here... i need to take a look what other addon developers do in this situation.

**Comment by darren12345** [comment]
It wasn't me that reported the other issue too was it? Memory like a sieve :)

Anyway, just tested it again and it appears to be working now so I am closing this for the moment. Thanks.
