### ISSUE TITLE
"Sort all bookmarks" should sort ALL bookmarks

### ISSUE THREAD

**Issue by blackwind** [ariacorrente/simple-sort-bookmarks#12]
The "Sort all bookmarks" button in advanced options only appears to operate on the Bookmarks Menu folder. It should sort Bookmarks Toolbar, Other Bookmarks, and Mobile Bookmarks as well.

**Comment by ariacorrente** [comment]
Thanks for the report, I don't use the other folders so I would never have noticed this problem.

To be honest, I realized only now that my addon is sorting those other folders automatically. Not to mention how much old stuff I just found in the "Other bookmarks" O_O .

The fix is ready and I'm going to publish a new small release on AMO.
